import type { Metadata } from "next";
import clsx from "clsx";
import "./globals.css";
import localFont from 'next/font/local'

const bentoga = localFont({ src: '../public/fonts/bentoga/Bentoga-Thin.otf' })
const satoshi = localFont({
  src: [
    {
      path: '../public/fonts/Satoshi/Fonts/OTF/Satoshi-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(satoshi.className, "antialiased bg-lightyellow text-red")}>
        {children}
      </body>
    </html>
  );
}
